const workShiftPermissions = [
  { code: "work_shifts.read", name: "Consultar turnos laborales" },
  { code: "work_shifts.manage", name: "Gestionar turnos laborales" },
];

const permissionCatalog = [
  ...workShiftPermissions,
  { code: "dashboard.read", name: "Consultar el dashboard" },
  { code: "products.read", name: "Consultar productos" },
  { code: "products.create", name: "Crear productos" },
  { code: "products.update", name: "Modificar productos" },
  { code: "products.delete", name: "Dar de baja productos" },
  { code: "categories.read", name: "Consultar categorías" },
  { code: "categories.create", name: "Crear categorías" },
  { code: "categories.update", name: "Modificar categorías" },
  { code: "categories.delete", name: "Dar de baja categorías" },
  { code: "suppliers.read", name: "Consultar proveedores" },
  { code: "suppliers.create", name: "Crear proveedores" },
  { code: "suppliers.update", name: "Modificar proveedores" },
  { code: "suppliers.delete", name: "Dar de baja proveedores" },
  { code: "employees.read", name: "Consultar empleados" },
  { code: "employees.create", name: "Crear empleados" },
  { code: "employees.update", name: "Modificar empleados" },
  { code: "employees.deactivate", name: "Dar de baja lógicamente empleados" },
  { code: "employees.delete", name: "Eliminar físicamente empleados" },
  { code: "sales.read", name: "Consultar ventas" },
  { code: "sales.create", name: "Registrar ventas" },
  { code: "sales.update", name: "Modificar ventas" },
  { code: "sales.delete", name: "Dar de baja ventas" },
  { code: "purchases.read", name: "Consultar compras" },
  { code: "purchases.create", name: "Registrar compras" },
  { code: "purchases.update", name: "Modificar compras" },
  { code: "purchases.delete", name: "Dar de baja compras" },
  { code: "balances.read", name: "Consultar balances" },
  { code: "balances.manage", name: "Gestionar balances" },
  { code: "transactions.read", name: "Consultar transacciones" },
  { code: "transactions.manage", name: "Gestionar transacciones" },
  { code: "stock_movements.read", name: "Consultar movimientos de stock" },
  { code: "stock_movements.create", name: "Registrar movimientos de stock" },
  { code: "users.read", name: "Consultar usuarios" },
  { code: "users.manage", name: "Gestionar usuarios" },
  { code: "roles.read", name: "Consultar roles y permisos" },
  { code: "roles.manage", name: "Gestionar roles y permisos" },
  { code: "commerce.update", name: "Modificar los datos del comercio" },
];

export { permissionCatalog, workShiftPermissions };
